config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/admin" => "admin#index", as: :admin_home
  get "/admin/users" => "admin#users", as: :admin_users
  get "/admin/reports" => "admin#reports", as: :admin_reports
  get "/admin/report_by_date" => "admin#report_by_date", as: :admin_report_by_date
  get "/admin/report_by_user" => "admin#report_by_user", as: :admin_report_by_user
  get "/" => "customer#index", as: :customer_home
  get "/cart" => "customer#cart", as: :customer_cart
  get "/orders" => "customer#orders", as: :customer_orders
  get "/clerk" => "clerk#index", as: :clerk_home
  get "/signin" => "sessions#new", as: :new_session
  post "/signin" => "sessions#create", as: :sessions
  # post "/set_active_menu" => "configs#set_active_menu", as: :set_active_menu
  post "/add_to_cart" => "cart_items#add", as: :add_to_cart
  post "/deliver_order" => "orders#deliver", as: :deliver_order
  delete "/logout" => "sessions#destroy", as: :destroy_session
  resources :users
  resources :menus
  resources :menu_items
  resources :cart_items
  resources :orders
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, presence: true
  validates :email, presence: true
  validates :role, presence: true
  has_secure_password
  has_many :orders
  has_many :cart_items

  def admin?
    role == "admin"
  end

  def clerk?
    role == "clerk"
  end

  def customer?
    role == "customer"
  end

  def self.customers
    User.where(role: "customer")
  end
  def self.clerks
    User.where(role: "clerk")
  end
  def self.owners
    User.where(role: "admin")
  end

  def cart_items_count
    cart_items.map { |cart_item|
      cart_item.amount
    }
      .reduce(0, :+)
  end

  def cart_total
    cart_items.map { |cart_item|
      cart_item.amount * cart_item.menu_item.price
    }
      .reduce(0, :+)
  end

  def self.walk_in_customer
    all.find(Config.walk_in_customer_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :ensure_admin_logged_in, only: [:new, :create]

  def new
    render "signup"
  end

  def create
    if current_user && current_user.admin?
      if ["Customer", "Admin", "Clerk"].include?(params[:role])
        role_lower = params[:role].downcase
      else
        redirect_to admin_users_path
      end
    else
      role_lower = "customer"
    end
    new_user = User.new(
      first_name: params[:first_name],
      last_name: params[:last_name],
      email: params[:email],
      password: params[:password],
      role: role_lower,
    )
    if not new_user.save()
      flash[:error] = new_user.errors.full_messages.join(", ")
    end
    if params[:source] == "admin"
      redirect_to admin_users_path
    else
      redirect_to customer_home_path
    end
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to admin_users_path
  end
end

app/views/users/signup.html.erb
<h1 class="RegisterTitle" >Welcome to Pupilfirst Café</h1>
<div class="Register" >
  <h1 class="Register--Title" >Register</h1>
  <div class="Register--FormContainer" >
    <%= form_with url: users_path, method: :post, class:"Register--Form" do |form|%>
      <%= form.text_field :first_name, placeholder: "First Name", class:"Register--FormInput" %>
      <%= form.text_field :last_name, placeholder: "Last Name", class:"Register--FormInput" %>
      <%= form.email_field :email, placeholder: "Email", class:"Register--FormInput" %>
      <%= form.password_field :password, placeholder: "Password", class:"Register--FormInput" %>
      <%= form.button "Sign Up", class:"Button Button__primary" %>
    <% end %>
    <p class="Register--Subtext" >Already have an account? <%= link_to "Login Here", sessions_path %></p>
  </div>
  <div></div>