config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/admin" => "admin#index", as: :admin_home
  get "/admin/users" => "admin#users", as: :admin_users
  get "/admin/reports" => "admin#reports", as: :admin_reports
  get "/admin/report_by_date" => "admin#report_by_date", as: :admin_report_by_date
  get "/admin/report_by_user" => "admin#report_by_user", as: :admin_report_by_user
  get "/" => "customer#index", as: :customer_home
  get "/cart" => "customer#cart", as: :customer_cart
  get "/orders" => "customer#orders", as: :customer_orders
  get "/clerk" => "clerk#index", as: :clerk_home
  get "/signin" => "sessions#new", as: :new_session
  post "/signin" => "sessions#create", as: :sessions
  # post "/set_active_menu" => "configs#set_active_menu", as: :set_active_menu
  post "/add_to_cart" => "cart_items#add", as: :add_to_cart
  post "/deliver_order" => "orders#deliver", as: :deliver_order
  delete "/logout" => "sessions#destroy", as: :destroy_session
  resources :users
  resources :menus
  resources :menu_items
  resources :cart_items
  resources :orders
end

app/controllers/customer_controller.rb
class CustomerController < ApplicationController
  skip_before_action :ensure_admin_logged_in
  before_action :ensure_customer_logged_in

  def index
    @active_menus = Menu.active_menus.order(name: :ASC)
    render "index"
  end

  def cart
    if current_user.cart_items_count == 0
      redirect_to "/"
    else
      render "cart"
    end
  end

  def orders
    render "orders"
  end

  def reports
    render "reports"
  end
end

app/views/customer/_menu.html.erb
<div class="CustomerMenu">
  <p class="CustomerMenu--Header"><%= menu.name %></p>
  <div class="CustomerMenu--TableContainer">
    <table class="CustomerMenu--Table" width="100%">
      <tbody>
        <% menu.menu_items.each do |menu_item| %>
          <tr>
            <td><%= menu_item.name %> </td>
            <td class="CustomerMenu--Price">₹<%= menu_item.price %> </td>
            <td>
              <%= image_tag(cloudinary_url(menu_item.picture.key, options = {width:230, height: 153,crop: :fill})) %>
            </td>
            <td><%= menu_item.description %> </td>
            <td>
              <div class="AddToCart">
                <%= form_with url: add_to_cart_path, method: :post do |form| %>
                  <%= form.hidden_field :user_id, value: @current_user.id %>
                  <div class="AddToCart--Container">
                    <div class="AddToCart--Upper">
                      <button type="button" class="AddToCart--Minus" onclick="decrease(<%=menu_item.id%>)">-</button>
                      <input name ="amount" id="cart_<%=menu_item.id%>" class="AddToCart--Number" readonly autocomplete="off" value="1">
                      <button type="button" class="AddToCart--Plus" onclick="increase(<%=menu_item.id%>)">+</button>
                    </div>
                    <%= form.hidden_field :menu_item_id, value: menu_item.id %>
                    <%= form.submit :Add, class:"AddToCart--Button" %>
                  </div>
                <% end %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/customer/cart.html.erb
<div class="CartTable" >
  <div class="CartTable--Header" >
    <p class="CartTable--Title" >My Cart</p>
    <p class="CartTable--Total">Total: <span class="CartTable--Total"> ₹<%= @current_user.cart_total %> </span></p>
  </div>
  <div class="CartTable--TableContainer">
    <table class="CartTable--Table" width="100%">
      <thead>
        <tr>
          <th>Name</th>
          <th>Image</th>
          <th>Quantity</th>
          <th>Price</th>
          <th>Modify</th>
          <th>Delete</th>
        </tr>
      </thead>
      <tbody>
        <% @current_user.cart_items.order(id: :ASC).each do |cart_item| %>
          <tr>
            <td>
              <%= cart_item.menu_item.name %>
            </td>
            <td>
              <%= image_tag(cloudinary_url(cart_item.menu_item.picture.key, options = {width:230, height: 153,crop: :fill})) %>
            </td>
            <td>
              <%= cart_item.amount %>
            </td>
            <td>
              ₹<%= cart_item.cost %>
            </td>
            <td>
              <div class="CartTable--FormContainer">
                <%= form_with url: "/cart_items/#{cart_item.id}", method: :patch do |form| %>
                  <input type="text" name="amount" placeholder="Quantity" autocomplete="off" >
                  <input type="submit" value="Change" class="Button Button__primary ChangeButton" >
                <% end %>
              </div>
            </td>
            <td>
              <%= form_with url:"/cart_items/#{cart_item.id}", method: :delete do |form| %>
                <%= form.submit "Delete", class:"Button Button__primary" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="CartTable--PlaceOrderForm">
      <p class="CartTable--BottomTotal" >
        ₹<%= @current_user.cart_total %>
      </p>
      <%= form_with url:"/orders", method: :post do |form| %>
        <%= form.hidden_field :user_id, value:@current_user.id %>
        <%= form.submit "Place Order", class:"Button Button__secondary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/customer/index.html.erb
<div class="CustomerUpper">
  <div class="CustomerActiveMenu">
  </div>
  <div class="CustomerCart">
    <p class="CustomerCart--Label">Cart : <%= @current_user.cart_items_count %> </p>
    <% unless @current_user.cart_items_count==0 %>
      <%= link_to "Checkout", customer_cart_path, class: "Button Button__primary" %>
    <% end %>
  </div>
</div>
<% @active_menus.each do |menu| %>
  <%= render partial: "customer/menu", locals: {
  menu: menu
} %>
<% end %>
<script type="text/javascript">
  function decrease(menu_item_id) {
    element=document.getElementById("cart_"+menu_item_id);
    element.value=Math.max(1,element.value-1)
  }
  function increase(menu_item_id) {
    document.getElementById("cart_"+menu_item_id).value++;
  }
</script>

app/views/customer/orders.html.erb
<div class="OrdersTable" >
  <p class="OrdersTable--Title" >My Orders</p>
  <div class="OrdersTable--Container">
    <table class="OrdersTable--Table" width="100%">
      <thead>
        <th>
          Order ID
        </th>
        <th>
          Date
        </th>
        <th>
          Total
        </th>
        <th>
          Status
        </th>
      </thead>
      <tbody>
        <% @current_user.orders.each do |order| %>
          <tr>
            <td>
              <a class="OrdersTable--OrderId" href="/orders/<%= order.id %>">Order #<%= order.id %></a>
            </td>
            <td>
              <%= order.date.strftime("%d %b %Y") %>
            </td>
            <td>
              ₹<%= order.amount %>
            </td>
            <td>
              <% if order.status %>
                Delivered
              <% else %>
                Pending
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>