config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/admin" => "admin#index", as: :admin_home
  get "/admin/users" => "admin#users", as: :admin_users
  get "/admin/reports" => "admin#reports", as: :admin_reports
  get "/admin/report_by_date" => "admin#report_by_date", as: :admin_report_by_date
  get "/admin/report_by_user" => "admin#report_by_user", as: :admin_report_by_user
  get "/" => "customer#index", as: :customer_home
  get "/cart" => "customer#cart", as: :customer_cart
  get "/orders" => "customer#orders", as: :customer_orders
  get "/clerk" => "clerk#index", as: :clerk_home
  get "/signin" => "sessions#new", as: :new_session
  post "/signin" => "sessions#create", as: :sessions
  # post "/set_active_menu" => "configs#set_active_menu", as: :set_active_menu
  post "/add_to_cart" => "cart_items#add", as: :add_to_cart
  post "/deliver_order" => "orders#deliver", as: :deliver_order
  delete "/logout" => "sessions#destroy", as: :destroy_session
  resources :users
  resources :menus
  resources :menu_items
  resources :cart_items
  resources :orders
end

app/views/layouts/_navbar.html.erb
<nav class="Navbar">
  <h1 class="Navbar--Branding"> <a href="/">Pupilfirst Café</a></h1>
  <div class="Navbar--Center">
    <ul class="Navbar--Menu">
      <% if @current_user %>
        <% if @current_user.admin? %>
          <li class="Navbar--MenuItem"> <%= link_to "Home", admin_home_path %> </li>
          <li class="Navbar--MenuItem"><a href="/admin/reports">Reports</a></li>
          <li class="Navbar--MenuItem"> <%= link_to "Users", admin_users_path %> </li>
        <% elsif @current_user.clerk? %>
          <li class="Navbar--MenuItem"> <%= link_to "Home", clerk_home_path %> </li>
        <% elsif @current_user.customer? %>
          <li class="Navbar--MenuItem"> <%= link_to "Home", customer_home_path %> </li>
          <li class="Navbar--MenuItem"> <%= link_to "Orders", customer_orders_path %> </li>
        <% end %>
      <% end %>
    </ul>
  </div>
  <div class="Navbar--Right">
    <ul class="Navbar--Menu">
      <li class="Navbar--MenuItem Navbar--MenuItem__Username">
        <% if @current_user %>
          Hi <%= @current_user.first_name %>
        </li>
        <li>
          <%= form_with url: destroy_session_path, method: :delete do |form| %>
            <%= form.button :Logout, class:"Button Button__primary" %>
          <% end %>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CafeteriaManagementRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "layouts/navbar" %>
    <% if flash[:error] %>
      <div id="FlashMessage" ><%= flash[:error] %> </div>
    <% end %>
    <main class="MainContent">
      <%= yield %>
    </main>
  </body>
</html>